name: Frequent Repository Heartbeat

on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'
  
  # Allows manual triggering for testing
  workflow_dispatch:

jobs:
  heartbeat:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      
      - name: Update activity
        run: |
          # Get current timestamp
          TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S %Z')
          echo "Running update at $TIMESTAMP"
          
          # Update the activity file
          ACTIVITY_FILE="activity.md"
          
          if [ ! -f "$ACTIVITY_FILE" ]; then
            echo "# Repository Activity Log" > "$ACTIVITY_FILE"
            echo "" >> "$ACTIVITY_FILE"
          fi
          
          # Keep only the last 100 entries (to avoid file growing too large)
          if [ -f "$ACTIVITY_FILE" ]; then
            tail -n 100 "$ACTIVITY_FILE" > "${ACTIVITY_FILE}.tmp"
            mv "${ACTIVITY_FILE}.tmp" "$ACTIVITY_FILE"
          fi
          
          # Add new timestamp
          echo "🔄 Update at $TIMESTAMP" >> "$ACTIVITY_FILE"
          
          # Commit and push changes
          git add "$ACTIVITY_FILE"
          git commit -m "chore: update at $TIMESTAMP [skip ci]"
          git push || {
            # If push fails, pull latest changes and try again
            git pull --rebase
            git push
          }
